"""DTOs for Meal Genie conversational AI."""

from pydantic import BaseModel
from typing import Optional, List, Literal


class MealGenieMessageDTO(BaseModel):
    """A single message in the conversation."""

    role: Literal["user", "assistant"]
    content: str


class MealGenieRequestDTO(BaseModel):
    """Request DTO for Meal Genie chat."""

    message: str
    conversation_history: Optional[List[MealGenieMessageDTO]] = None


class MealGenieResponseDTO(BaseModel):
    """Response DTO for Meal Genie chat."""

    success: bool
    response: Optional[str] = None
    error: Optional[str] = None


# Recipe Generation DTOs


class GeneratedIngredientDTO(BaseModel):
    """Ingredient data generated by AI."""

    ingredient_name: str
    ingredient_category: str
    quantity: Optional[float] = None
    unit: Optional[str] = None


class GeneratedRecipeDTO(BaseModel):
    """Recipe data generated by AI (not yet saved)."""

    recipe_name: str
    recipe_category: str
    meal_type: str
    diet_pref: Optional[str] = None
    total_time: Optional[int] = None
    servings: Optional[int] = None
    directions: Optional[str] = None
    notes: Optional[str] = None
    ingredients: List[GeneratedIngredientDTO] = []


class RecipeGenerationRequestDTO(BaseModel):
    """Request DTO for generating a recipe via Meal Genie."""

    message: str
    conversation_history: Optional[List[MealGenieMessageDTO]] = None
    generate_image: bool = True


class RecipeGenerationResponseDTO(BaseModel):
    """Response DTO containing generated recipe + optional images."""

    success: bool
    recipe: Optional[GeneratedRecipeDTO] = None
    reference_image_data: Optional[str] = None  # Base64 encoded (1:1 square)
    banner_image_data: Optional[str] = None  # Base64 encoded (21:9 ultrawide)
    ai_message: Optional[str] = None  # Friendly message from AI
    needs_more_info: bool = False  # True if AI is asking follow-up questions
    error: Optional[str] = None
