"""API router for cooking tips."""

from fastapi import APIRouter, HTTPException

from app.ai.dtos import CookingTipResponseDTO
from app.ai.services import get_cooking_tip_service

router = APIRouter()


@router.get("", response_model=CookingTipResponseDTO)
async def get_cooking_tip() -> CookingTipResponseDTO:
    """
    Get a random cooking tip generated by AI.

    Returns:
        Response with a cooking tip on success
    """
    try:
        service = get_cooking_tip_service()
        result = service.generate_tip()

        if not result.success:
            raise HTTPException(
                status_code=500, detail=result.error or "Tip generation failed"
            )

        return result

    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Tip generation failed: {str(e)}")
