"""API router for cooking tips."""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.ai.dtos import CookingTipResponseDTO
from app.ai.services import get_cooking_tip_service
from app.api.auth import require_pro
from app.database.db import get_session
from app.models.user import User
from app.services.usage_service import UsageService

router = APIRouter()


@router.get("", response_model=CookingTipResponseDTO)
async def get_cooking_tip(
    session: Session = Depends(get_session),
    current_user: User = Depends(require_pro),
) -> CookingTipResponseDTO:
    """
    Get a random cooking tip generated by AI.

    Returns:
        Response with a cooking tip on success
    """
    try:
        service = get_cooking_tip_service()
        result = service.generate_tip()

        if not result.success:
            raise HTTPException(
                status_code=500, detail=result.error or "Tip generation failed"
            )

        # Track usage (silent fail - don't break AI feature for tracking issues)
        try:
            UsageService(session, current_user.id).increment("ai_suggestions_requested")
        except Exception:
            pass

        return result

    except HTTPException:
        raise
    except ValueError as e:
        raise HTTPException(status_code=500, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Tip generation failed: {str(e)}")
