"""Add is_ai_generated column to recipe table

Revision ID: 3f4a5b6c7d8e
Revises: 68b0d25d47f7
Create Date: 2026-02-20

Adds a boolean flag to track whether a recipe was generated by the AI assistant.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f4a5b6c7d8e'
down_revision: Union[str, Sequence[str], None] = '68b0d25d47f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'recipe',
        sa.Column('is_ai_generated', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.create_index('ix_recipe_is_ai_generated', 'recipe', ['is_ai_generated'])


def downgrade() -> None:
    op.drop_index('ix_recipe_is_ai_generated', table_name='recipe')
    op.drop_column('recipe', 'is_ai_generated')
