"""Add is_ai_generated column to recipe table

Revision ID: b2c3d4e5f6a7
Revises: a0b1c2d3e4f5
Create Date: 2026-02-20

Adds a boolean flag to track whether a recipe was generated by the AI assistant.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a7'
down_revision: Union[str, Sequence[str], None] = 'a0b1c2d3e4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'recipe',
        sa.Column('is_ai_generated', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.create_index('ix_recipe_is_ai_generated', 'recipe', ['is_ai_generated'])


def downgrade() -> None:
    op.drop_index('ix_recipe_is_ai_generated', table_name='recipe')
    op.drop_column('recipe', 'is_ai_generated')
