"""app/dtos/recipe_generation_dtos.py

Pydantic DTOs for the AI recipe generation flow (prompt-based).
Renamed from wizard_dtos.py — all Wizard* prefixes dropped.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field

from .nutrition_dtos import NutritionFactsDTO


# ── Shared DTOs ──────────────────────────────────────────────────────────────


class GeneratedIngredientDTO(BaseModel):
    """Ingredient data generated by AI."""

    ingredient_name: str
    ingredient_category: str
    quantity: Optional[float] = None
    unit: Optional[str] = None


# ── Request DTOs ─────────────────────────────────────────────────────────────


class RecipeGenerationPreferencesDTO(BaseModel):
    """Optional preferences to guide AI recipe generation."""

    category: Optional[str] = None
    dietary: Optional[str] = None
    difficulty: Optional[str] = None
    servings: Optional[int] = Field(None, ge=1)
    meal_type: Optional[str] = None


class RecipeGenerationRequestDTO(BaseModel):
    """Request DTO for prompt-based AI recipe generation."""

    prompt: str = Field(..., min_length=1, max_length=500)
    preferences: Optional[RecipeGenerationPreferencesDTO] = None
    allowed_categories: List[str] = Field(default_factory=list)
    generate_image: bool = False
    estimate_nutrition: bool = True


# ── Response DTOs ────────────────────────────────────────────────────────────


class RecipeGeneratedDTO(BaseModel):
    """Full recipe DTO returned by AI generation (prompt-based or assistant)."""

    recipe_name: str
    recipe_category: str = "other"
    meal_type: str = "dinner"
    diet_pref: Optional[str] = None
    description: Optional[str] = None
    prep_time: Optional[int] = None
    cook_time: Optional[int] = None
    total_time: Optional[int] = None
    difficulty: Optional[str] = None
    servings: Optional[int] = None
    directions: Optional[str] = None
    notes: Optional[str] = None
    ingredients: List[GeneratedIngredientDTO] = []


class RecipeGenerationResponseDTO(BaseModel):
    """Response DTO for prompt-based AI recipe generation."""

    success: bool
    recipe: Optional[RecipeGeneratedDTO] = None
    nutrition_facts: Optional[NutritionFactsDTO] = None
    reference_image_data: Optional[str] = None
    banner_image_data: Optional[str] = None
    error: Optional[str] = None
