"""Shared configuration for AI services."""

import os

DEFAULT_GEMINI_MODEL = "gemini-3.5-flash"
DEFAULT_GEMINI_ASSISTANT_MODEL = "gemini-3.5-flash"
DEFAULT_GEMINI_IMAGE_MODEL = "gemini-3.1-flash-image"

GEMINI_MODEL = os.getenv("GEMINI_MODEL", DEFAULT_GEMINI_MODEL)
GEMINI_ASSISTANT_MODEL = os.getenv("GEMINI_ASSISTANT_MODEL", DEFAULT_GEMINI_ASSISTANT_MODEL)
GEMINI_IMAGE_MODEL = os.getenv("GEMINI_IMAGE_MODEL", DEFAULT_GEMINI_IMAGE_MODEL)
